# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 700)
        Form.setStyleSheet("background-color: #f5f5f5;")

        # 主垂直布局
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")

        # 标题
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setObjectName("label_title")
        self.label_title.setText("基于主题模型的关键词提取系统")
        self.label_title.setStyleSheet("""
            font-size: 24px;
            font-weight: bold;
            color: #333;
            qproperty-alignment: AlignCenter;
        """)
        self.verticalLayout.addWidget(self.label_title)

        # 主内容区域
        self.frame_main = QtWidgets.QFrame(Form)
        self.frame_main.setStyleSheet("""
            background-color: white;
            border-radius: 10px;
            padding: 15px;
        """)
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_main.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_main.setSpacing(20)
        self.verticalLayout.addWidget(self.frame_main)

        # 水平布局 - 工具箱和表格
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # 工具箱 - 设置固定宽度
        self.toolBox = QtWidgets.QToolBox(Form)
        self.toolBox.setStyleSheet("""
            QToolBox {
                background-color: white;
                border-radius: 8px;
                border: 1px solid #ddd;
            }
            QToolBox::tab {
                background-color: #f0f0f0;
                border: 1px solid #ddd;
                border-radius: 5px;
                margin-right: 5px;
            }
            QToolBox::tab:selected {
                background-color: #e0e0e0;
                font-weight: bold;
            }
        """)
        self.toolBox.setObjectName("toolBox")
        self.toolBox.setFixedWidth(500)  # 设置固定宽度

        # 选择文件页
        self.page_file = QtWidgets.QWidget()
        self.page_file.setObjectName("page_file")
        self.verticalLayout_file = QtWidgets.QVBoxLayout(self.page_file)
        self.verticalLayout_file.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_file.setSpacing(20)
        self.verticalLayout_file.setObjectName("verticalLayout_file")

        self.label_file = QtWidgets.QLabel(self.page_file)
        self.label_file.setObjectName("label_file")
        self.label_file.setText("选择需要提取关键词的文件")
        self.label_file.setStyleSheet("font-size: 16px; font-weight: bold;")
        self.verticalLayout_file.addWidget(self.label_file)

        self.label_desc = QtWidgets.QLabel(self.page_file)
        self.label_desc.setObjectName("label_desc")
        self.label_desc.setText("支持格式: Word文档(.docx), PDF(.pdf), 图像(.jpg, .png)")
        self.label_desc.setStyleSheet("color: #666;")
        self.label_desc.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_file.addWidget(self.label_desc)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_file.addItem(spacerItem)

        self.horizontalLayout_file = QtWidgets.QHBoxLayout()
        self.horizontalLayout_file.setSpacing(20)
        self.horizontalLayout_file.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout_file.setObjectName("horizontalLayout_file")

        self.pushButton_file = QtWidgets.QPushButton(self.page_file)
        self.pushButton_file.setObjectName("pushButton_file")
        self.pushButton_file.setText("选择文件")
        self.pushButton_file.setStyleSheet("""
            QPushButton {
                background-color: #4CAF50;
                color: white;
                border: none;
                border-radius: 5px;
                padding: 10px 20px;
                font-size: 14px;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
        """)
        self.horizontalLayout_file.addWidget(self.pushButton_file)

        self.pushButton_folder = QtWidgets.QPushButton(self.page_file)
        self.pushButton_folder.setObjectName("pushButton_folder")
        self.pushButton_folder.setText("选择文件夹")
        self.pushButton_folder.setStyleSheet("""
            QPushButton {
                background-color: #2196F3;
                color: white;
                border: none;
                border-radius: 5px;
                padding: 10px 20px;
                font-size: 14px;
            }
            QPushButton:hover {
                background-color: #0b7dda;
            }
        """)
        self.horizontalLayout_file.addWidget(self.pushButton_folder)

        self.verticalLayout_file.addLayout(self.horizontalLayout_file)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_file.addItem(spacerItem2)

        self.toolBox.addItem(self.page_file, "")

        # 重训练模型页
        self.page_train = QtWidgets.QWidget()
        self.page_train.setObjectName("page_train")
        self.verticalLayout_train = QtWidgets.QVBoxLayout(self.page_train)
        self.verticalLayout_train.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_train.setSpacing(20)
        self.verticalLayout_train.setObjectName("verticalLayout_train")

        self.label_train = QtWidgets.QLabel(self.page_train)
        self.label_train.setObjectName("label_train")
        self.label_train.setText("模型训练配置")
        self.label_train.setStyleSheet("font-size: 16px; font-weight: bold;")
        self.verticalLayout_train.addWidget(self.label_train)

        self.gridLayoutWidget = QtWidgets.QWidget(self.page_train)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")

        self.label_model = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_model.setObjectName("label_model")
        self.label_model.setText("选择模型:")
        self.label_model.setStyleSheet("font-size: 14px;")
        self.gridLayout.addWidget(self.label_model, 0, 0, 1, 1)

        self.comboBox_model = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_model.setObjectName("comboBox_model")
        self.comboBox_model.addItem("LSI")
        self.comboBox_model.addItem("LDA")
        self.comboBox_model.setStyleSheet("""
            QComboBox {
                padding: 8px;
                border: 1px solid #ddd;
                border-radius: 5px;
                min-width: 120px;
            }
        """)
        self.gridLayout.addWidget(self.comboBox_model, 0, 1, 1, 1)

        self.label_topics = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_topics.setObjectName("label_topics")
        self.label_topics.setText("主题数量:")
        self.label_topics.setStyleSheet("font-size: 14px;")
        self.gridLayout.addWidget(self.label_topics, 1, 0, 1, 1)

        self.spinBox_topics = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_topics.setObjectName("spinBox_topics")
        self.spinBox_topics.setMinimum(1)
        self.spinBox_topics.setMaximum(100)
        self.spinBox_topics.setValue(10)
        self.spinBox_topics.setStyleSheet("""
            QSpinBox {
                padding: 8px;
                border: 1px solid #ddd;
                border-radius: 5px;
                min-width: 60px;
            }
        """)
        self.gridLayout.addWidget(self.spinBox_topics, 1, 1, 1, 1)

        self.horizontalSlider_topics = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_topics.setObjectName("horizontalSlider_topics")
        self.horizontalSlider_topics.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_topics.setMinimum(1)
        self.horizontalSlider_topics.setMaximum(100)
        self.horizontalSlider_topics.setValue(10)
        self.horizontalSlider_topics.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_topics.setTickInterval(10)
        self.gridLayout.addWidget(self.horizontalSlider_topics, 2, 0, 1, 2)

        self.pushButton_retrain = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_retrain.setObjectName("pushButton_retrain")
        self.pushButton_retrain.setText("重训练模型")
        self.pushButton_retrain.setStyleSheet("""
            QPushButton {
                background-color: #ff9800;
                color: white;
                border: none;
                border-radius: 5px;
                padding: 10px 20px;
                font-size: 14px;
            }
            QPushButton:hover {
                background-color: #e68a00;
            }
        """)
        self.gridLayout.addWidget(self.pushButton_retrain, 3, 0, 1, 2)

        self.verticalLayout_train.addWidget(self.gridLayoutWidget)
        self.toolBox.addItem(self.page_train, "")

        # 增加语料页
        self.page_corpus = QtWidgets.QWidget()
        self.page_corpus.setObjectName("page_corpus")
        self.verticalLayout_corpus = QtWidgets.QVBoxLayout(self.page_corpus)
        self.verticalLayout_corpus.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_corpus.setSpacing(20)
        self.verticalLayout_corpus.setObjectName("verticalLayout_corpus")

        self.label_corpus = QtWidgets.QLabel(self.page_corpus)
        self.label_corpus.setObjectName("label_corpus")
        self.label_corpus.setText("增加训练语料")
        self.label_corpus.setStyleSheet("font-size: 16px; font-weight: bold;")
        self.verticalLayout_corpus.addWidget(self.label_corpus)

        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_corpus.addItem(spacerItem3)

        self.horizontalLayout_corpus = QtWidgets.QHBoxLayout()
        self.horizontalLayout_corpus.setSpacing(20)
        self.horizontalLayout_corpus.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout_corpus.setObjectName("horizontalLayout_corpus")

        self.pushButton_add_file = QtWidgets.QPushButton(self.page_corpus)
        self.pushButton_add_file.setObjectName("pushButton_add_file")
        self.pushButton_add_file.setText("添加文件")
        self.pushButton_add_file.setStyleSheet("""
            QPushButton {
                background-color: #4CAF50;
                color: white;
                border: none;
                border-radius: 5px;
                padding: 10px 20px;
                font-size: 14px;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
        """)
        self.horizontalLayout_corpus.addWidget(self.pushButton_add_file)

        self.pushButton_add_folder = QtWidgets.QPushButton(self.page_corpus)
        self.pushButton_add_folder.setObjectName("pushButton_add_folder")
        self.pushButton_add_folder.setText("添加文件夹")
        self.pushButton_add_folder.setStyleSheet("""
            QPushButton {
                background-color: #2196F3;
                color: white;
                border: none;
                border-radius: 5px;
                padding: 10px 20px;
                font-size: 14px;
            }
            QPushButton:hover {
                background-color: #0b7dda;
            }
        """)
        self.horizontalLayout_corpus.addWidget(self.pushButton_add_folder)

        self.verticalLayout_corpus.addLayout(self.horizontalLayout_corpus)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_corpus.addItem(spacerItem4)

        self.toolBox.addItem(self.page_corpus, "")

        self.horizontalLayout.addWidget(self.toolBox)

        # 结果表格
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setObjectName("tableView")
        self.tableView.setStyleSheet("""
            QTableView {
                border: 1px solid #ddd;
                border-radius: 8px;
            }
            QHeaderView::section {
                background-color: #f0f0f0;
                padding: 8px;
            }
        """)
        self.horizontalLayout.addWidget(self.tableView)

        self.verticalLayout_main.addLayout(self.horizontalLayout)

        # 底部状态栏
        self.statusBar = QtWidgets.QStatusBar(Form)
        self.statusBar.setObjectName("statusBar")
        self.statusBar.setSizeGripEnabled(False)
        self.verticalLayout.addWidget(self.statusBar)

        self.retranslateUi(Form)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "主题模型关键词提取系统"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_file), _translate("Form", "文件选择"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_train), _translate("Form", "模型训练"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_corpus), _translate("Form", "语料管理"))
        self.pushButton_retrain.setText(_translate("Form", "重训练模型"))
        self.label_model.setText(_translate("Form", "选择模型:"))
        self.comboBox_model.setItemText(0, _translate("Form", "LSI"))
        self.comboBox_model.setItemText(1, _translate("Form", "LDA"))
        self.label_topics.setText(_translate("Form", "主题数量:"))
